
const http=require('http'),fs=require('fs'),path=require('path');
const PORT=Number(process.env.PORT||7071),HOST=process.env.HOST||'0.0.0.0',PUBLIC=path.join(__dirname,'public');
function send(res,s,b,t='application/json'){res.writeHead(s,{'Content-Type':t,'Cache-Control':'no-store','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET,POST,OPTIONS'});res.end(t.includes('json')?JSON.stringify(b):b)}
function body(req){return new Promise((ok,no)=>{let d='';req.on('data',c=>d+=c);req.on('end',()=>{try{ok(d?JSON.parse(d):{})}catch{no(Error('Invalid JSON body'))}});req.on('error',no)})}
function tc(s){return String(s||'').replace(/\w\S*/g,w=>w[0].toUpperCase()+w.slice(1).toLowerCase())}
function infer(q){let m=String(q||'').match(/(?:build|create|plan|implement|migrate|deploy)\s+(?:an?\s+)?(.+?)(?:\s+(?:where|that|with|including|from|for|to)\b|[.,]|$)/i);return m?tc(m[1]).slice(0,100):'New Project'}
function fallback(q){const n=infer(q);return {projectName:n,projectObjective:q,estimatedSprints:4,epic:{title:n,features:[
{title:'Discovery and Planning',userStories:[{title:'Define delivery requirements',acceptanceCriteria:['Project scope is documented','Stakeholders approve the delivery requirements'],recommendedSprint:'Sprint 1',dependencies:[],tasks:[{title:'Confirm project scope'},{title:'Document requirements'},{title:'Review technical dependencies'}]}]},
{title:'Implementation',userStories:[{title:'Deliver the core solution',acceptanceCriteria:['Core solution is implemented','Functional validation is completed'],recommendedSprint:'Sprint 2',dependencies:['Discovery and Planning'],tasks:[{title:'Implement core solution'},{title:'Perform functional testing'},{title:'Resolve implementation findings'}]}]},
{title:'Handover and Closure',userStories:[{title:'Complete operational handover',acceptanceCriteria:['Handover documentation is complete','Operations accepts the handover'],recommendedSprint:'Sprint 4',dependencies:['Implementation'],tasks:[{title:'Prepare handover documentation'},{title:'Complete knowledge transfer'},{title:'Obtain project sign-off'}]}]}
]},risks:[],status:'DRAFT',source:'PROJECTPILOT_FALLBACK'}}
function normalize(b){if(b.plan)b=b.plan;const q=b.project_requirement||b.projectRequirement||'';if(!b.epic&&!b.features)return fallback(q||'Create a new project');const e=b.epic||{title:b.projectName||'New Project',features:b.features||[]};return {projectName:b.projectName||e.title||infer(q),projectObjective:b.projectObjective||q||'',estimatedSprints:b.estimatedSprints||4,epic:{title:e.title||b.projectName,features:(e.features||[]).map(f=>({title:f.title,userStories:(f.userStories||f.stories||[]).map(s=>({title:s.title,acceptanceCriteria:s.acceptanceCriteria||[],recommendedSprint:s.recommendedSprint||'',dependencies:s.dependencies||[],tasks:(s.tasks||[]).map(t=>typeof t==='string'?{title:t}:t)}))}))},risks:b.risks||[],status:'DRAFT',source:'MOVEWORKS_AI'}}
function serve(p,res){const rel=p==='/'?'index.html':p.replace(/^\/+/,'');const fp=path.normalize(path.join(PUBLIC,rel));if(!fp.startsWith(PUBLIC)||!fs.existsSync(fp))return send(res,404,{error:'Not found'});const ext=path.extname(fp);const m={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8'};return send(res,200,fs.readFileSync(fp),m[ext]||'application/octet-stream')}
const srv=http.createServer(async(req,res)=>{try{if(req.method==='OPTIONS')return send(res,204,'','text/plain');const u=new URL(req.url,`http://${req.headers.host}`);if(req.method==='GET'&&u.pathname==='/api/health')return send(res,200,{ok:true,version:'3.0.0',mode:'DEMO',environment:process.env.WEBSITE_SITE_NAME?'AZURE_APP_SERVICE':'LOCAL_OR_CODESPACES'});if(req.method==='POST'&&u.pathname==='/api/ai-plan'){const b=await body(req);if(!b.project_requirement&&!b.projectRequirement&&!b.plan&&!b.epic&&!b.features)return send(res,400,{error:'project_requirement or structured plan is required'});return send(res,200,normalize(b))}if(req.method==='POST'&&u.pathname==='/api/approve-plan'){const b=await body(req);if(!b.plan)return send(res,400,{error:'plan is required'});return send(res,200,{mode:'DEMO',message:'Approval recorded. Azure DevOps creation remains disabled in this demo.',created:[{type:'Epic',id:1001,title:b.plan.epic.title}]})}return serve(u.pathname,res)}catch(e){console.error(e);send(res,500,{error:e.message})}});
srv.listen(PORT,HOST,()=>console.log(`Project Command Center v3.0 running on ${HOST}:${PORT}`));
