
const http=require('http'),fs=require('fs'),path=require('path'),https=require('https');
const PORT=process.env.PORT||7071,PUBLIC=path.join(__dirname,'public');
function send(res,s,b,t='application/json'){res.writeHead(s,{'Content-Type':t,'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type'});res.end(t.includes('json')?JSON.stringify(b):b)}
function body(req){return new Promise((ok,no)=>{let d='';req.on('data',c=>d+=c);req.on('end',()=>{try{ok(d?JSON.parse(d):{})}catch(e){no(e)}});req.on('error',no)})}
function title(s){return s.replace(/\w\S*/g,w=>w[0].toUpperCase()+w.slice(1).toLowerCase())}
function infer(q){let m=q.match(/(?:build|create|plan|migrate|implement)\s+(?:an?\s+)?(.+?)(?:\s+(?:where|that|with|including|from|for)\b|[.,]|$)/i);return m?title(m[1]).slice(0,80):'New Project'}
function fallback(q){let n=infer(q);return {projectName:n,projectObjective:q,estimatedSprints:4,epic:{title:n,features:[{title:'Discovery and Planning',userStories:[{title:'Define delivery requirements',acceptanceCriteria:['Scope is documented','Stakeholders approve requirements'],recommendedSprint:'Sprint 1',dependencies:[],tasks:[{title:'Confirm scope'},{title:'Document requirements'},{title:'Review dependencies'}]}]},{title:'Implementation',userStories:[{title:'Deliver core solution',acceptanceCriteria:['Core solution is implemented','Validation is completed'],recommendedSprint:'Sprint 2',dependencies:['Discovery and Planning'],tasks:[{title:'Implement solution'},{title:'Perform testing'},{title:'Resolve findings'}]}]},{title:'Handover and Closure',userStories:[{title:'Complete operational handover',acceptanceCriteria:['Documentation is complete','Operations accepts handover'],recommendedSprint:'Sprint 4',dependencies:['Implementation'],tasks:[{title:'Prepare handover document'},{title:'Complete knowledge transfer'},{title:'Obtain sign-off'}]}]}]},risks:[],status:'DRAFT',source:'PROJECTPILOT_FALLBACK'}}
function normalize(b){if(b.plan)b=b.plan;if(!b.epic&&!b.features)return fallback(b.project_requirement||b.projectRequirement||'Create a new project');let ep=b.epic||{title:b.projectName,features:b.features};return {projectName:b.projectName||ep.title||'New Project',projectObjective:b.projectObjective||b.project_requirement||'',estimatedSprints:b.estimatedSprints||4,epic:{title:ep.title||b.projectName,features:(ep.features||[]).map(f=>({title:f.title,userStories:(f.userStories||f.stories||[]).map(s=>({title:s.title,acceptanceCriteria:s.acceptanceCriteria||[],recommendedSprint:s.recommendedSprint||'',dependencies:s.dependencies||[],tasks:(s.tasks||[]).map(t=>typeof t==='string'?{title:t}:t)}))}))},risks:b.risks||[],status:'DRAFT',source:'MOVEWORKS_AI'}}
function configured(){return !!(process.env.AZDO_ORG&&process.env.AZDO_PROJECT&&process.env.AZDO_PAT)}
function azdo(method,payloadPath,payload){return new Promise((ok,no)=>{let d=JSON.stringify(payload),a=Buffer.from(':'+process.env.AZDO_PAT).toString('base64');let r=https.request({hostname:'dev.azure.com',path:`/${encodeURIComponent(process.env.AZDO_ORG)}/${encodeURIComponent(process.env.AZDO_PROJECT)}${payloadPath}`,method,headers:{Authorization:`Basic ${a}`,'Content-Type':'application/json-patch+json','Content-Length':Buffer.byteLength(d)}},x=>{let o='';x.on('data',c=>o+=c);x.on('end',()=>x.statusCode<300?ok(JSON.parse(o)):no(Error(`Azure DevOps ${x.statusCode}: ${o}`)))});r.on('error',no);r.write(d);r.end()})}
async function create(type,title,parent){let p=[{op:'add',path:'/fields/System.Title',value:title},{op:'add',path:'/fields/System.Tags',value:'ProjectPilot-AI;PM-Approved'}];if(parent)p.push({op:'add',path:'/relations/-',value:{rel:'System.LinkTypes.Hierarchy-Reverse',url:`https://dev.azure.com/${process.env.AZDO_ORG}/_apis/wit/workItems/${parent}`}});return azdo('POST',`/_apis/wit/workitems/$${encodeURIComponent(type)}?api-version=7.1`,p)}
async function hierarchy(plan){let out=[],e=await create('Epic',plan.epic.title);out.push({type:'Epic',id:e.id,title:plan.epic.title});for(let f of plan.epic.features){let fi=await create('Feature',f.title,e.id);out.push({type:'Feature',id:fi.id,title:f.title});for(let s of f.userStories){let si=await create('User Story',s.title,fi.id);out.push({type:'User Story',id:si.id,title:s.title});for(let t of s.tasks){let ti=await create('Task',t.title,si.id);out.push({type:'Task',id:ti.id,title:t.title})}}}return out}
const srv=http.createServer(async(req,res)=>{try{if(req.method==='OPTIONS')return send(res,204,'','text/plain');let u=new URL(req.url,`http://${req.headers.host}`);
if(req.method==='GET'&&u.pathname==='/api/health')return send(res,200,{ok:true,version:'2.1.0',mode:configured()?'AZURE_DEVOPS':'DEMO'});
if(req.method==='POST'&&u.pathname==='/api/ai-plan'){let b=await body(req);if(!b.project_requirement&&!b.projectRequirement&&!b.plan&&!b.epic&&!b.features)return send(res,400,{error:'project_requirement or structured plan is required'});return send(res,200,normalize(b))}
if(req.method==='POST'&&u.pathname==='/api/approve-plan'){let b=await body(req);if(!b.plan)return send(res,400,{error:'plan required'});if(!configured())return send(res,200,{mode:'DEMO',message:'Approval recorded; Azure DevOps creation simulated.',created:[{type:'Epic',id:1001,title:b.plan.epic.title}]});return send(res,200,{mode:'AZURE_DEVOPS',message:'Approved hierarchy created.',created:await hierarchy(b.plan)})}
let f=u.pathname==='/'?'index.html':u.pathname.slice(1),fp=path.join(PUBLIC,f);if(fs.existsSync(fp))return send(res,200,fs.readFileSync(fp),f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':'text/html');send(res,404,{error:'Not found'})
}catch(e){console.error(e);send(res,500,{error:e.message})}});
srv.listen(PORT,()=>console.log(`ProjectPilot AI Phase 2.1 running at http://localhost:${PORT}`));
